### ISSUE TITLE
JMS source artifacts are not functional

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/jms#3]
_From @mbogoevici on June 15, 2016 14:52_

Currently we generate the JMS source artifacts based on the starter, but we do not include any JMS client libraries, nor do we set up any connection factories. Consequently, the `JmsAutoConfiguration` is not triggered, and the generated artifacts fail to start.

_Copied from original issue: spring-cloud/spring-cloud-stream-app-starters#135_

**Comment by sabbyanandan** [comment]
_From @cforce on July 25, 2016 16:29_

Is there a time line for this fix?

**Comment by artembilan** [comment]
Closed in favor of #1
